# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 2.2.5-mondified
maven_group = com.metacontent.cobblenav
archives_name = cobblenav
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.17.2
fabric_api_version = 0.116.6+1.21.1
neoforge_version = 21.1.51

kotlinforforge_version = 5.10.0
fabric_kotlin_version = 1.13.6+kotlin.2.2.20
cobblemon_version = 1.7.0+1.21.1

# Integrations
mal_neoforge_version = occT2ebf
mal_fabric_version = 1.8.0
counter_neoforge_version = 1.6.1-neoforge-1.5.2
counter_fabric_version = 1.6.1-fabric-1.5.2
